### ISSUE TITLE
unsaved changes warning message if user tries to exit without saving

### ISSUE THREAD

**Issue by clindsey** [preble/InsideJob#1]
I launch InsideJob, make some changes, exit, and launch minecraft only to realize I forgot to save. Is it possible to add a warning dialog to say something like 'are you sure you want to exit without saving?'

**Comment by preble** [comment]
That's a good suggestion.  It's on my todo list.  Thanks, Chris!

**Comment by preble** [comment]
I've added prompts on window/app-closing and world-switching and pushed 1.0.1 beta 1 (available now in source or as a binary download).
