### ISSUE TITLE
Will not open

### ISSUE THREAD

**Issue by deadeye7997** [preble/InsideJob#15]
I click on it and it says that there is no app to open it.  Please help.

**Comment by preble** [comment]
What version of Mac OS X are you running?  Inside Job presently requires 10.6 and up.

**Comment by deadeye7997** [comment]
Oh sorry i didnt realize i am running 10.5

**Comment by deadeye7997** [comment]
How can i make my mac a 10.6

**Comment by preble** [comment]
Mac OS X 10.6 ("Snow Leopard") is a $30 upgrade from 10.5.  Note however that 10.6 only runs on Intel Macs.
