### ISSUE TITLE
beta items

### ISSUE THREAD

**Issue by crazypotatos** [preble/InsideJob#18]
Ok i noticed that you added the values, but how do you update the application? is there somewhere where i can put those values or something? or is there something im supposed to download?

**Comment by ghost** [comment]
Currently, you could do "show package contents" on Inside Job and navigate to: Contents > Resources and replace the Items.csv.

Right now, I'm not aware of any auto-update mechanism.

**Comment by crazypotatos** [comment]
Ok i just downloaded the raw file and it worked fine. Thanks! All that needs to be updated would be the item pictures.

**Comment by ghost** [comment]
Nickloose has a build that does more than my altering of the CSV:

https://github.com/nickloose/InsideJob/commit/dc0fbfc1f02a859df82fcf93fddac92abd1428b6
