### ISSUE TITLE
After you download.

### ISSUE THREAD

**Issue by TheMurmur** [preble/InsideJob#2]
What am I supposed to do with the folder after I download it? I don't see an app or anything. =(

**Comment by preble** [comment]
Make sure you downloaded InsideJob100.zip (under Download Packages) and not the source.  InsideJob100.zip should expand into Inside Job.app.

**Comment by ghost** [comment]
When i expand i get just a folder called preble-InsideJob-0703516 and if i just change the .zip to .app it says cannot run.

**Comment by preble** [comment]
It sounds like you have downloaded the source.  Go to the main http://github.com/preble/InsideJob page, click the Downloads button, and then click, under "Download Packages", InsideJob100.zip.

**Comment by ghost** [comment]
Yep. :) Working

**Comment by clindsey** [comment]
I downloaded the source, navigated to the folder in terminal, ran `xcodebuild` and it generated InsideJob.app in the build/release/ directory.
