### ISSUE TITLE
doesn't work on your version of Mac os x ?

### ISSUE THREAD

**Issue by cadarok** [preble/InsideJob#22]
When I try to open inside job there is a pop up that say your mac os x version does is not able to open this application.

**Comment by erisdev** [comment]
Inside Job requires Mac OS X 10.6; you're probably running an older version.

Supporting older versions of OS X would require a non-trivial amount of work for little gain, so it's not likely to happen unless somebody else who really, really needs it is willing to do the work.

**Comment by cadarok** [comment]
I have Mac OS X 10.6 Snow Leopard. The problem is that Inside Job needs to update to v1.0.3 because Minecraft had an up date some time ago and and can have may world not in order for 1-5 and v1.0.2 on inside job is looking for the worlds but can't see them.
