### ISSUE TITLE
Update for Beta 1.3

### ISSUE THREAD

**Issue by zackonsax** [preble/InsideJob#23]
Could you possibly create a newer version that works with the newest patch of Minecraft that came out today? And btw thanks I loved this program when it worked

**Comment by nickloose** [comment]
I've added the new Items for Beta 1.3 in my fork.
if you have xcode installed you can build it yourself!
I hope I find the time to add to load worlds with different names…
https://github.com/nickloose/InsideJob

**Comment by zackonsax** [comment]
How do you use xcode to do that? I have it downloaded

**Comment by nickloose** [comment]
You have to open the InsideJob.xcodeproj in xcode form the source code folder 
(if you haven't downloadet at already https://github.com/nickloose/InsideJob/zipball/master )

in xocde you have to click the build and run button, and the InsideJob.app is the InsideJob/Build/Release folder…
