### ISSUE TITLE
Update Please?

### ISSUE THREAD

**Issue by ghost** [preble/InsideJob#25]
Insidejob is a very high quality inventory editor, I will admit. Yet the names of objects need to be updated, as well as the Beta 1.2 and 1.3 features. For example, I cannot create a new world in Beta 1.3 that is compatible with this system. It simply says a world doesn't exist in that slot when there clearly is. My point is that Insidejob desperately requires a update to Beta 1.3 and below. Please consider this and inform me when it is updated, or if at all.

**Comment by preble** [comment]
Inside Job 1.0.2 adds beta 1.3 items, however world names outside World1-World5 are not yet supported.
