### ISSUE TITLE
Can't connect to a level.

### ISSUE THREAD

**Issue by doven45** [preble/InsideJob#26]
everytime i open inside job it says please create a single player world in this slot, even though i already have a world loaded in that slot

**Comment by erisdev** [comment]
Inside Job hasn't been updated for 1.3 yet. In addition to new items, the update has changed the level format and introduced support for named worlds (other than World 1, World 2, etc.).

**Comment by eiik97** [comment]
should I just wait for inside job to update for 1.3?
please update it soon!
