### ISSUE TITLE
1.0.2 not able to backspace in text box?

### ISSUE THREAD

**Issue by kentopia01** [preble/InsideJob#29]
Hi Mr Preble,

Your application, inside job, is a fantastic app and runs without crashing, however, there is a slight minor issue. When i type text into the item finder, i find that i cannot backspace. However, i still can press the (X) button, so its not too much of a problem, but if i type one letter wrongly, i would have to press the X and restart my search all over again.

If its not too much of a request, i really do hope you would fix this issue, for me and for all the mine crafters out there. Happy mine crafting :D

BlueXaphriox

**Comment by preble** [comment]
This is fixed in Inside Job 1.1.1.  Thanks for reporting it!
