### ISSUE TITLE
Inventory remains on previous world when clicking an empty world slot

### ISSUE THREAD

**Issue by ghost** [preble/InsideJob#3]
First of all, great work on this!!  I'm very pleased and impressed to find a quality OS X tool for Minecraft.

The only thing I've noticed so far is that when you click on an empty world slot, the inventory for the previously selected world stays selected.  For example, I currently have worlds 1-4 in Minecraft (5 is empty).  When I click on the "5" button, I get an appropriate error message; however, I would expect to see either the selected inventory to be cleared (since an empty world has no inventory), or the world selection box at the top switch back to the previously selected world.

Currently, the previous world's inventory appears (e.g. World 4), while the selection box for the empty world (World 5) is selected.

This is pretty minor, but I can see how it would lead to some confusion.  I haven't played around with it too much, but I'm also not quite sure what would happen if you then tried to save changes you made to the previous world's inventory while the empty world's inventory was selected (i.e. I'm not sure if this is more than just a visual error, or if the code also has the "World 5" object selected as well).

Hopefully that made some sort of sense.  Anyway, great work again!

**Comment by preble** [comment]
I can see how that would be confusing; I'll put this on my list to fix.  Thanks for filing the issue!

**Comment by preble** [comment]
I've made some improvements to the handling of worlds that could not be loaded and have pushed 1.0.1 beta 1 (available now in source and as a binary download).  The inventory displays should empty and you will not be able to add items to the 'dead' world.
