### ISSUE TITLE
inside problem

### ISSUE THREAD

**Issue by SkuxxDeluxee** [preble/InsideJob#32]
when i click on inside job it says that i havent created a world on minecraft in any slot, and i have tried countless times to fix it but nothing works, wht do i do?? and i have OS X version 10.6 so there is no reason why it shouldent work!

**Comment by preble** [comment]
This is probably related to the new way Minecraft saves worlds (in rename-able slots).  Inside Job does not yet support this storage style.  Sorry for the inconvenience!
