### ISSUE TITLE
There is no Wool block item!

### ISSUE THREAD

**Issue by lolmop** [preble/InsideJob#4]
Hey, awsome app! There doesn't seem to be a Wool block as a selectable item. You can obtain these from hitting sheep. Just wondering if you could add this item in a future release please!

Thankyou

**Comment by preble** [comment]
Thanks!  I believe the "wool block" is labeled as "cloth" in the item finder.  Let me know if this is not the case and what you believe the item id should be and I'll fix it.

**Comment by bobybob** [comment]
yes thats true it is a cloth block.. i was wondering the same thing before
