### ISSUE TITLE
downloaded but wont open  :(  PLEASE READ!!!!!!!!!!!!! preble

### ISSUE THREAD

**Issue by hellocool** [preble/InsideJob#41]
i have already downloaded the 1.1.1 inside job a billion times and all of the sources that I've lead me the place that you can download it. then I open it with the Archive thingy on the mac that default is on and I look at the pic. of the lock thingy (your logo) and there is a big X thing over it and when I try to open it it say that it cant run on this version of mac.  PLEASE HELP ME

**Comment by preble** [comment]
What version of Mac OS X do you have?  Inside Job only runs on Mac OS X 10.6 and up.

**Comment by hellocool** [comment]
ohhhhhhh thats why. can you plzzzzz try make it so it can run on 10.5 and up. ppppppplllllzzzzzzzzzzz

**Comment by preble** [comment]
Sorry; Inside Job relies on some 10.6-only features.

**Comment by hellocool** [comment]
also when are you coming out with the new version

**Comment by hellocool** [comment]
like what
