### ISSUE TITLE
Needs updates for up to 1.9

### ISSUE THREAD

**Issue by ghost** [preble/InsideJob#46]

**Comment by epetousis** [comment]
Go here:
https://github.com/Kaikz/InsideJob

**Comment by nbburns** [comment]
There is an update, it's been forked check here: https://github.com/jake8/InsideJob
Just download and build

**Comment by kylekz** [comment]
My fork allows items to be added without code changes. You just need to add the item name and ID into items.csv, and the image named "block-ITEMID.png", replacing ITEMID with of course, the item ID. However, jake8 (and I suspect McSpider soon)'s versions have better features/UI updates. I have a half finished item adding window in mine, someone can finish it if they wish. I have no intention in doing so. I may just add a pull request to someone elses with the dynamic item code.
